appium/appium-remote-debugger

- lib/remote-debugger-rpc-client.js
- lib/remote-debugger.js
- lib/webkit-remote-debugger.js
Rather than erroring when there are no apps present, just keep going. Otherwise reconnecting too soon causes the remote debugger on the device to freak out and stop responding. The client will disconnect when the client feels like it.
@scottdixon This, in addition to some changes once this lands, fixes the getting context multiple times issue.
> Do not disconnect when no apps are present

- lib/remote-debugger.js
- test/unit/remote-debugger-specs.js
We have had some issues with iOS 9+ and webviews connecting then hanging. Fix this by remembering the actually connected app.
Original PR: appium/appium#5800
> Keep track of updated remote debugger app

- lib/remote-debugger.js
Rather than letting it fall through and act like a page was actually selected if all the retries are used up. This way we throw the proper error.
> Reset page dictionary if url is wrong

- lib/message-handlers.js
Rather than always finding a new app id, only do it if we've actually lost the one we are connected to.
> Fix handling of application disconnects

- package.json
There is a memory leak in the `ws` version we use. Bumping to the fixed version (1.0.1).
https://nodesecurity.io/advisories/ws_buffer-leak
> Update ws library

- lib/helpers.js
- lib/message-handlers.js
- lib/remote-debugger-rpc-client.js
- lib/remote-debugger.js
- lib/webkit-remote-debugger.js
- lib/webkit-rpc-client.js
Some objects that we log have stringified functions on them, which makes the logs less useful by cluttering with non-information. For logging, remove those properties.
> Clean up logging of objects

- lib/helpers.js
- lib/message-handlers.js
- lib/remote-debugger.js
- test/helpers/remote-debugger-server.js
- test/unit/remote-debugger-specs.js
Traditional webviews return an app with multiple pages associated with it. We would find the one we wanted. In wkwebviews each page is mapped to its own app. So rather than looking at a single app, we need to look at all of them.
This changes the webview ids from simple integers (which were app ids) to composites of the app and the page. For UIWebviews the webviews will be, for app `PID:1234` with four pages, something like `1234.1`, `1234.2`, `1234.3`, and `1234.4`. For WkWebviews we will get ids like `1234.0`, `1235.0`, `1236.0`, and `1237.0`.
Since there is no _a priori_ way to tell what the id would be for a particular webview in the previous scheme, this should not be a breaking change.
See discussion https://github.com/appium/appium/issues/5839
> Better mapping of pages, to allow multiple wkwebviews on sims

- lib/remote-debugger.js
Rather than simply looking through the current record, look through all the records we have already to see if the page has been found in the background. This should (a) speed things up and (b) make things more reliable, as we don't need to interact with the remote debugger so much.
> Check for the right app better

- lib/remote-debugger.js
Instead of logging application list as
```
dbug RemoteDebugger Notified that a new application PID:96989 has connected
dbug RemoteDebugger Current applications available:
dbug RemoteDebugger Application: 'PID:96987'
dbug RemoteDebugger     id: '"PID:96987"'
dbug RemoteDebugger     name: '"Safari"'
dbug RemoteDebugger     bundleId: '"com.apple.mobilesafari"'
dbug RemoteDebugger     isProxy: 'false'
dbug RemoteDebugger     hostId: 'undefined'
dbug RemoteDebugger     isActive: '1'
dbug RemoteDebugger Application: 'PID:96989'
dbug RemoteDebugger     id: '"PID:96989"'
dbug RemoteDebugger     name: '""'
dbug RemoteDebugger     bundleId: '"com.apple.WebKit.WebContent"'
dbug RemoteDebugger     isProxy: 'true'
dbug RemoteDebugger     hostId: '"PID:96987"'
dbug RemoteDebugger     isActive: '1'
dbug …
```
> Better logging for promise

- lib/helpers.js
- lib/message-handlers.js
- lib/remote-debugger-message-handler.js
- lib/remote-debugger.js
- lib/remote-messages.js
- test/helpers/remote-debugger-server.js
Mostly this is cosmetic. The crux of the matter is adding `WIRAutomaticallyPause: false` to the arguments sent on the `_rpc_forwardSocketSetup:` call (setting the sending id before choosing the page). Without this the connection to the app succeeds, but almost immediately the remote debugger disconnects the app and we are left with no way to automate it.
This appears to be fully backward compatible.
> Add support for iOS 10

- lib/remote-debugger.js
When we check the apps we are breaking out of the selection when we have the right app, but not keeping track of what that app is. This means we end up getting _an_ app but not necessarily the _right_ app.
So keep track of the id and the page dictionary where the page is.
> Make sure we keep track of the page we have chosen

- lib/remote-debugger.js
Condition was backwards, so sometimes we would end up, inexplicably, in the wrong app and timeout.
> Change direction of condition

- lib/remote-debugger.js
- test/helpers/remote-debugger-server.js
- test/unit/remote-debugger-specs.js
What I observed is remote debugger hangs sometimes if connected to webview with empty url or about:blank. May be because at that point it is still trying to load page. Here I totally neglect empty url and have option of ignoring `about:blank` so that it doesn't hang anymore.
> don't connect to app if url is `about:blank` or empty url

- lib/remote-debugger.js
Otherwise we cannot get webviews that do not have any content yet. Appium's webview tests fail with this check.
> Remove requirement of having a non-blank url

- lib/remote-debugger.js
- lib/webkit-rpc-client.js
Addressing #42.
I went with a simple 5 sec timeout. Let me know if it needs to be configured through a capability.
> Ensuring Appium times out gracefully if webkit does not return a response

- lib/remote-debugger-message-handler.js
- lib/remote-debugger-rpc-client.js
- lib/remote-debugger.js
- lib/webkit-rpc-client.js
- test/unit/remote-debugger-specs.js
Fix a number of cases in which we are mishandling errors, or we don't have the requisite information to process incoming messages.
This, in conjunction with a couple of driver issues, cleans up the unhandled rejection errors.
> Fix error handling

- lib/helpers.js
Currently if there is not yet any app connected to a bundleId we zip through the retries (since there is nothing to retry. Use the default app instead.
Hoping this has some affect on https://github.com/appium/appium/issues/7587
> Add try of generic app when none found

- lib/webkit-remote-debugger.js
If [ios-webkit-debug-proxy](https://github.com/google/ios-webkit-debug-proxy) is started as Google [recommends](https://github.com/google/ios-webkit-debug-proxy#start-the-proxy) it listens generically on the default port (9221) and chooses another port (sequentially through open ports) for each connected device and simulator.
The call, then, to `localhost:9221/json` produces a list of the devices connected.
Starting:
```
$ /usr/local/Cellar/ios-webkit-debug-proxy/1.7/bin/ios_webkit_debug_proxy
Listing devices on :9221
Connected :9223 to i(am)Phone (xxxxx)
Connected :9222 to SIMULATOR (SIMULATOR)
```
Hitting `localhost:9221/json`:
```
[{
"deviceId": "SIMULATOR",
"deviceName": "SIMULATOR",
"url": "localhost:9222"
},{
"deviceId": "xxxxx",
"deviceName": "i(am)Phone",
"url": "localhost:9223" …
```
> Allow basic i-w-d-p functioning

- lib/logger.js
- package.json
- test/helpers/remote-debugger-server.js
- test/helpers/webkit-remote-debugger-server.js
Stop using the deprecated `appium-logger`.
> Move to logger from appium-support

- lib/webkit-remote-debugger.js
- lib/webkit-rpc-client.js
We timeout webkit requests after 5s currently, because sometimes they hang (see #43). But some systems might need more time (or less, I suppose), so make it configurable through a `webkitResponseTimeout` option, which will be an iOS capability.
Addresses: https://github.com/appium/appium/issues/7977
> Make webkit response timeout configurable

- lib/remote-debugger.js
1. Add timeout for page readiness check (and option to pass in the timeout, as `pageReadyTimeout` (in ms)).
2. Add optional async function parameter to `navToUrl` to handle any possible popup during url navigation. What this does is up to the calling code.
> Allow alert handler to be passed in to url nav function

- lib/remote-debugger-message-handler.js
- lib/remote-debugger-rpc-client.js
- lib/remote-debugger.js
- lib/remote-messages.js
- lib/webkit-rpc-client.js
Add methods `startConsole` and `stopConsole` to begin and end capture of the JS console from the connected app.
The callback sent to `startConsole` is passed an entry whenever a log line is generated on the device. The entry for something like `console.log('HI ALL');` on the device would be:
```
{ source: 'console-api',
level: 'log',
text: 'HI ALL',
type: 'log',
line: 8,
column: 16,
url: 'http://localhost:4994/test/guinea-pig',
repeatCount: 1,
parameters: [ { type: 'string', value: 'HI ALL' } ],
stackTrace:
[ { functionName: 'global code',
url: 'http://localhost:4994/test/guinea-pig',
scriptId: '1',
lineNumber: 8,
columnNumber: 16 } ] }
```
> Add handler for starting/stopping JS console capture

- lib/webkit-remote-debugger.js
- lib/webkit-rpc-client.js
Recent changes disturbed the defaulting of `host` for real devices.
Fixes https://github.com/appium/appium/issues/10347
> Make sure webkit host is set

- lib/remote-debugger-rpc-client.js
- lib/remote-debugger.js
- lib/webkit-rpc-client.js
iOS 11.3 real devices sometimes reply to the start console log, so handle that otherwise it hangs.
> Add webkit handler for Console.enable event

- lib/remote-debugger-message-handler.js
- lib/remote-debugger-rpc-client.js
- lib/remote-debugger.js
- lib/remote-messages.js
- test/unit/remote-debugger-specs.js
Safari uses the deprecated [Page.getCookies](https://chromedevtools.github.io/devtools-protocol/tot/Page#method-getCookies) and [Page.deleteCookie](https://chromedevtools.github.io/devtools-protocol/tot/Page#method-deleteCookie) methods, rather than those from the [Network domain](https://chromedevtools.github.io/devtools-protocol/tot/Network). This means that it also does not have access to setting cookies.
> Add methods for getting the cookies and delete a particular cookie

- lib/remote-debugger-rpc-client.js
- package.json
In Appium's packages, we use [uuid-js](https://www.npmjs.com/package/uuid-js) everywhere but here, so change here so we're only supporting a single package
```
$ npm ls uuid
appium@1.8.0-beta /Users/isaacmurchie/code/appium
├─┬ appium-ios-driver@2.5.1
│ └─┬ appium-remote-debugger@3.18.0
│   └── uuid@3.3.2  deduped
├─┬ request@2.87.0
│ └── uuid@3.3.2
└─┬ wd@1.10.1
└─┬ request@2.85.0
└── uuid@3.3.2  deduped
$npm ls uuid-js
appium@1.8.0-beta /Users/isaacmurchie/code/appium
├─┬ appium-base-driver@3.1.0
│ └── uuid-js@0.7.5
├─┬ appium-espresso-driver@1.0.0-beta.11
│ └─┬ appium-base-driver@2.33.0
│   └── uuid-js@0.7.5  deduped
├─┬ appium-ios-driver@2.5.1
│ └── uuid-js@0.7.5  deduped
├─┬ appium-mac-driver@1.2.0
│ └─┬ appium-base-driver@2.33.0
│   └── uuid-js@0.7.5  deduped
├─┬ …
```
> Switch from uuid to uuid-js

- lib/webkit-rpc-client.js
Perhaps bluebird cannot properly do its job, so we try to distinguish the actual error class it on our own
> Change the way errors are handled in catch

- lib/remote-debugger.js
https://gist.github.com/Joskony/12233f06431430fdb6be6bcf3650139f#file-appium-log-L612
> Avoid "Cannot read property 'promise' of undefined" error while checking for app

- lib/remote-debugger.js
See https://github.com/appium/appium/issues/11683.
With WebKit we do not do the same logic for frame navigation, so this is not necessary.
> Make sure that allowNavigationWithoutReload exists before calling

- .travis.yml
- lib/atoms.js
- lib/helpers.js
- lib/message-handlers.js
- lib/remote-debugger-message-handler.js
- lib/remote-debugger-rpc-client.js
- lib/remote-debugger.js
- lib/remote-messages.js
- lib/webkit-rpc-client.js
- test/helpers/remote-debugger-server.js
- test/helpers/webkit-remote-debugger-server.js
- test/unit/remote-debugger-specs.js
- test/unit/remote-messages-specs.js
**The problem:** In iOS 12.2 the remote debugger stopped working, because instead of using the entire protocol, all communication is now wrapped in `Target.sendMessageToTarget` commands and `Target.dispatchMessageFromTarget` messages (which prior to iOS 12.2 were not known at all by Safari).
This PR implements, for iOS 12.2, this protocol change.
As I worked on this I also cleaned some stuff up, which muddled the diffs a bit, for which I apologize.
Confirmation that this works through real functional tests (with some necessary changes at the driver level):
- iOS driver: https://travis-ci.org/appium/appium-ios-driver/builds/504089881
- XCUITest driver: https://travis-ci.org/appium/appium-xcuitest-driver/builds/505734791
This works for simulators only. Beginning work on real device …
> Add support for iOS 12.2

- lib/helpers.js
- lib/remote-debugger-rpc-client.js
- lib/webkit-remote-debugger.js
- lib/webkit-rpc-client.js
Add support for iOS 12.2 on real devices. For this to work `ios-webkit-debug-proxy` needs to be the latest from HEAD.
This duplicates a bunch of logic, but as the package is structured now that is necessary. Once this is in I will allocate some time to refactor this to use the same message handler system, which should remove the duplication.
> Handle iOS 12.2 for real devices

- lib/message-handlers.js
- lib/remote-debugger.js
If we are in the middle of navigating to a page, do not send page change notifications, which cause confusion.
> Do not send page change event when navigating

- package.json
This [commit](https://github.com/appium/appium-remote-debugger/commit/ce95e92cb5e0cc4c6c11799d79cf1b7a1cbb3bbc) added the use of appium-support.util.compareVersions which is only available in appium-support version [2.26.0](https://github.com/appium/appium-support/commit/d03c1973bca7b42eec4830c99e710c93d44990f3) and above.
> Update appium-support minimum version.

- lib/rpc-client.js
It seems that sometimes the Web Inspector sends empty `targetDestroyed` events, which leads to errors since we're trying to get a property on the information, which would be `undefined`.
See line 10207 of https://dev.azure.com/srinivasansekar/java-client/_build/results?buildId=164
> Make sure empty target events are handled correctly

- README.md
- lib/message-handlers.js
Remove the stripping of `isKey` from equality check on page change.
> Fix handling of page change

- .travis.yml
- lib/remote-debugger-message-handler.js
- lib/remote-debugger.js
- lib/rpc-client.js
- test/functional/safari-e2e-specs.js
It turns out that on iOS 13 there is no relation between target id and page id (earlier page id `1` would be `page-1` as a target).
So handle mapping the three variables (app id, page id, target id).
Add Xcode 11/iOS 13 to Travis build.
> fix: Properly save reported targets

- lib/remote-debugger-message-handler.js
- lib/remote-debugger.js
- lib/rpc-client.js
The handling I had used would fail when there was lots of chatter, since the synchrony was not upheld.
Also return all the pages when selecting the app, even if the page is not the appropriate one, to help with maintaining page changes within the driver.
Tested with `appium-xcuitest-driver` safari tests, on iOS 12.2, 12.1, and 13.0.
> fix: better handling of targets

- package.json
In the recent shift in implementation in this repo, there were a bunch of dependencies that are no longer being used. So remove them.
> fix: remove dependencies we no longer use

- lib/rpc-client.js
On iOS 12 the targets are always `page-<page id>`, while the id can be different, and needs to be waited for.
So, when we can, just compute the target id.
> fix: compute target if we can

- lib/helpers.js
- lib/remote-debugger.js
Right now, we only ever allow a user to get a webview associated with the main bundle under test. That is, we check the apps the Web Inspector returns against the bundle identifier for the app under test, and only return those.
There is no theoretical reason for this. While we may at some point want to be able to do multiple bundle ids, this PR simply allows an option to sent to the remote debugger to include Safari, if it is there, in the apps.
This has the effect that if an app opens Safari (as in https://github.com/appium/appium/issues/13171) from their app, they can automate it.
> feat: add option to include Safari in apps to listen for

- lib/rpc-client-real-device.js
- lib/rpc-client-simulator.js
The remote debugger keeps listening to the socket until it is fully destroyed, which leads to weird logs where we've finished a session but events keep happening. This is easily rectified.
> fix: do not receive rpc messages when 'disconnected'

- lib/helpers.js
- lib/remote-debugger-message-handler.js
- lib/remote-debugger.js
- lib/remote-messages.js
- test/functional/safari-e2e-specs.js
iOS 13 stopped allowing us to install a self-signed certificate, at least in the way we had been. This means that asynchronous execution also stopped working (see https://github.com/appium/appium/issues/13184). 
@umutuzgur found the `Runtime.awaitPromise` function in [WebKit](https://github.com/WebKit/webkit/blob/master/Source/JavaScriptCore/inspector/protocol/Runtime.json#L230-L245) and this PR implements the functionality of asynchronous execution using it.
Unfortunately the function is relatively new, so versions that don't have it fall back to polling for the result to exist. Luckily timeouts are still handled by the Selenium atom.
> fix: use promises instead of http/https for async execute

- lib/helpers.js
- lib/message-handlers.js
- lib/remote-debugger.js
- lib/rpc-client.js
- test/functional/safari-e2e-specs.js
**Breaking change**
Simplify how connected apps are treated. Mostly, do not wait after setting the connection key in the Web Inspector, then allow them to be handled asynchronously.
> fix: connection issues

- bin/web_inspector_proxy.js
- gulpfile.js
- lib/helpers.js
- lib/remote-debugger-message-handler.js
- lib/remote-debugger.js
- lib/remote-messages.js
- lib/rpc-client.js
- package.json
The next iteration in trying to get the protocol right. I've mimicked what Safari does on a Web Inspector session, and it seems to work much better now for both systems using the `Target` API and those using the old style.
Run against reproduction cases noted by @wswebcreation such as https://github.com/appium/appium/issues/13171 and https://github.com/appium/appium/issues/13248
> refactor: try to get the protocol right

- .travis.yml
- bin/web_inspector_proxy.js
- lib/message-handlers.js
- lib/remote-debugger-message-handler.js
- lib/remote-debugger-real-device.js
- lib/remote-debugger.js
- lib/rpc-client-real-device.js
- lib/rpc-client-simulator.js
- lib/rpc-client.js
- package.json
- test/functional/safari-e2e-specs.js
Use `async-lock` to make sure that the callbacks that adjust the application dictionary do not do so at the same time.
Also do a couple of other things:
1. Change `logFullResponse ` to `logAllCommunication` and use `appium-ios-device` to do this logging. This will continue to work through the calling code.
1. Ensure `appium-ios-device` gets the `isSimulator` parameter for creating Web Inspector service.
This ought to help support lower iOS versions (see https://github.com/appium/appium/issues/13388). Tests for iOS 9.3 fail with current master (https://travis-ci.org/appium/appium-remote-debugger/jobs/603818016) but work with this branch (https://travis-ci.org/appium/appium-remote-debugger/jobs/603816787).
> fix: make sure that app dict is not modified at the same time

- lib/logger.js
- lib/remote-debugger.js
- lib/remote-messages.js
- lib/rpc-client-real-device.js
- lib/rpc-client-simulator.js
- package.json
I had set the `emulateUserGesture` flag to `true` since it is what Safari sends. But in iOS 13+ this somehow bypasses the popup blocking in MobileSafari (so even set to true, new windows can be open).
I had also accidentally removed the prefix to the logger.
> fix: do not use user gestures

- lib/message-handlers.js
- lib/remote-debugger.js
- lib/remote-messages.js
- lib/rpc-client.js
- lib/rpc-message-handler.js
There were a number of places where callbacks were in the wrong place, so, for instance, an event would come in and be passed up to the RemoteDebugger from the RPC client, only to be passed back down to the RPC client.
So, move some of those around into the right places.
> refactor: move callbacks into correct places

- lib/helpers.js
- lib/message-handlers.js
- lib/remote-debugger.js
- test/unit/helpers-specs.js
Use apps with the bundle identifier `"*"`.
In doing this there was some code that could be yanked relating to old platforms that this version does not support.
Related to https://github.com/appium/appium/issues/13622
> feat: allow '*' as bundle id reported by Safari

- lib/helpers.js
- lib/remote-debugger.js
Allow an array of additional bundle identifiers to be passed in. These will be added to the list of bundle ids looked for when finding attached apps.
This is needed sometimes when app resigning changes the behaviour of the Web Inspector for reasons we are not entirely understanding.
> feat: allow passing in a list of additional possible bundle identifiers

- package.json
Update `appium-base-driver` in the v4 line of `appium-remote-debugger`.
> chore: update appium-base-driver

- lib/remote-debugger.js
It can happen that the math makes the retries be 0. But we need to try at least once.
> fix: always do the loop once in async execute

- lib/remote-debugger.js
There is no reason to ignore apps with empty urls. All the `appium-xcuitest-driver` tests run with this change (https://travis-ci.org/imurchie/appium-xcuitest-driver/builds/633862057)
> fix: do not ignore empty urls

- lib/helpers.js
Automatically find SafariViewController apps if available.
> fix: add safariviewcontroller bundle id to standard list

- lib/remote-debugger.js
- lib/rpc-client.js
There turns out to be no reason to wait for these calls to return.
> fix: do not wait for reply on setup commands

- lib/message-handlers.js
- lib/remote-debugger-real-device.js
- lib/remote-debugger.js
- lib/rpc-client-real-device.js
- lib/rpc-client-simulator.js
- lib/rpc-client.js
- lib/rpc-message-handler.js
- test/functional/safari-e2e-specs.js
Node has a great library for [event handling](https://nodejs.org/api/events.html#events_class_eventemitter). This package has been passing callbacks around to handle all the asynchronous messaging of the Web Inspector, which has outlived its usefulness.
So replace everything with `EventEmitter`. This is a **breaking change** due to the change in external events (adding an error parameter).
After this approach is vetted and in the module, it can be extended so that users of `appium-remote-debugger` can listen for whatever event form the Web Inspector they want to implement services.
> refactor: use EventEmitter instead of passing callbacks all over

- lib/remote-debugger-real-device.js
- lib/remote-debugger.js
- lib/rpc-message-handler.js
- test/functional/safari-e2e-specs.js
On real devices the internal listeners were not being initialized, so nothing was getting through. I've tested this thoroughly through `appium-xcuitest-driver` on both MobileSafari and hybrid apps and it works with this change.
> fix: get real devices working correctly

- lib/remote-debugger.js
Add a timeout to the `connect` function, which makes it wait for there to be apps reported. One there is at least one app it returns, or returns the empty app list as it used to.
Default to`0` so the behaviour is not changed. This will be configurable through the driver at the clients' discretion.
> feat: add timeout to connect, defaulting to 0

- lib/remote-debugger.js
- lib/rpc-message-handler.js
- test/functional/html/frameset.html
- test/functional/html/subframe1.html
- test/functional/html/subframe2.html
- test/functional/html/subframe3.html
- test/functional/safari-e2e-specs.js
On iOS 12.1 MobileSafari within a frame the `window` object gets reset (or we have a different window object?) when going through the atom. But since the code injected is known and stable, and also just retrieving values with no side effects, we can just run it directly.
> fix: handle async execute on iOS without awaitPromise

- lib/helpers.js
- test/unit/helpers-specs.js
iOS 13.4 uses `WIRTypeWebPage` as the web page type, so that must be accepted.
See https://github.com/appium/appium/issues/13948
> feat: add WIRTypeWebPage as an accepted web page type

- lib/rpc-client.js
- lib/rpc-message-handler.js
On iOS 13.4 there started to be target replacement during the normal flow of events. 
To handle, catch the `Target.didCommitProvisionalTarget` event and keep track, so when the correct target is destroyed, the new target can be used as a replacement.
As with all target handling, there is no page associated with it, so tracking is made more difficult.
> feat: handle new provisional target creation

- lib/message-handlers.js
- lib/rpc-client.js
A little more tweaking of the target lifecycle. Handle provisional target addition, which could be tracked but as of now there is no need, since a target update event always gets fired before the old target is destroyed, and it contains all the information needed for its use.
Also better handle deleting targets, so we don't delete the wrong one.
> fix: ignore add target event if provisional

- .travis.yml
Once Travis supports Xcode 11.4 we will add that, since there were changes between it and 11.3.
> build: move to iOS 13.3 in travis

- lib/helpers.js
- lib/remote-debugger.js
- test/unit/helpers-specs.js
Easier to just throw.
Plus, a simple benchmark shows that `try`/`catch` for control flow is very inefficient
```
[12:51:44] assert/catch x 36,599 ops/sec ±8.25% (60 runs sampled)
[12:51:51] if/then x 164,072,843 ops/sec ±1.51% (82 runs sampled)
[12:51:51] Fastest is if/then
```
> refactor: clean up parameter error handling

- lib/rpc/rpc-client.js
`Target.exists` was removed from WebKit ([rev](https://trac.webkit.org/browser/webkit/trunk/Source/JavaScriptCore/inspector/protocol/Target.json?rev=251227), [diff](https://trac.webkit.org/changeset?reponame=webkit&new=251227%40trunk%2FSource%2FJavaScriptCore%2Finspector%2Fprotocol%2FTarget.json&old=238192%40trunk%2FSource%2FJavaScriptCore%2Finspector%2Fprotocol%2FTarget.json)) in 13.4.
> fix: do not send Target.exists on iOS 13.4

- lib/mixins/execute.js
- lib/protocol/index.js
- lib/remote-debugger.js
- lib/rpc/remote-messages.js
- lib/rpc/rpc-client.js
Separate the protocol messages from the RPC generation, which is iOS specific. I've been working on integrating Chrome and this is a first step. Also makes the protocol easier to handle.
> refactor: move protocol out of rpc generation

- lib/rpc/rpc-client.js
For now, the `Target` domain communication is only when safari &&  12.2+, but according to https://github.com/appium/appium/issues/14604 `WKwebview` also requires the Target domain communication.
We have logic to make `this.isTargetBased` `false` to disable the Target communication style, so I think we can simply make `this.isTargetBased` `true` for iOS 12.2+.
I tested below steps with iOS 12.0, 12.4, iOS 13.0 and 13.6 simulators. iOS 12.0 raised `'Target' domain was not found` error once, but made `this.isTargetBased` false
1. Launch te ui-catalog app
2. Open the WebView section
3. Switch to WebView context
4. Back
5. Select the WebView section again
- Then, below logs appear
I'll test for a real device later
> feat: make isTargetBased true by default

- lib/mixins/connect.js
- lib/mixins/message-handlers.js
- lib/rpc/rpc-message-handler.js
Before
```
[debug] [RemoteDebugger] Debugger got a message for '_rpc_reportCurrentState:' and have no handler, doing nothing.
```
After
```
[debug] [RemoteDebugger] Received connected current state: "WIRAutomationAvailabilityNotAvailable"
[debug] [RemoteDebugger] Received connected current state: "WIRAutomationAvailabilityAvailable"
```
This command seems to change when 'remote automation' state changes in settings app > safari > advanced > remote automation
> feat: add _rpc_reportCurrentState handler for iOS 14

- lib/webkit-remote-debugger.js
- package.json
We still need to use version 4 of this module until appium-ios-driver is fully deprecated, so it makes sense to get rid of the deprecated modules that it is using
> chore: Remove deprecated dependencies

- development-notes.md
Related to https://github.com/appium/appium-remote-debugger/pull/274
Then, you can find Web Inspector's protocol like:
```
{
"__argument": {
"WIRApplicationIdentifierKey": "PID:2447",
"WIRMessageDataTypeKey": "WIRMessageDataTypeFull",
"WIRDestinationKey": "8B7C5766-E28E-478B-B62E-D2B2F6B0E16B",
"WIRMessageDataKey": "{\"method\":\"Target.dispatchMessageFromTarget\",\"params\":{\"targetId\":\"page-11\",\"message\":\"{\\\"method\\\":\\\"Debugger.scriptParsed\\\",\\\"params\\\":{\\\"scriptId\\\":\\\"41\\\",\\\"url\\\":\\\"https://apis.google.com/_/scs/abc-static/_/js/k=gapi.gapi.en.PlpnwD4HYro.O/m=gapi_iframes,googleapis_client/rt=j/sv=1/d=1/ed=1/rs=AHpOoo-D4573md5GmdJHX15d0lc3SoObhA/cb=gapi.loaded_0\\\",\\\"startLine\\\":0,\\\"startColumn\\\":0,\\\"endLine\\\":353,\\\"endColumn\\\":0,\\\"isCo …
```
> docs: add an example for simulator in development notes

- README.md
- package.json
- scripts/common.js
Fixed scripts associated with atoms as minimal way so that `npm run build:atoms` can generate atoms as same as previously.
This won't include more changes in `scripts` for now to keep the change minimal.
> fix: fix scripts for atoms

- lib/protocol/index.js
- lib/remote-debugger.js
Added all available commands in `Page` from https://github.com/WebKit/WebKit/blob/main/Source/JavaScriptCore/inspector/protocol/Page.json
Current getCookies does not have any input in xcuitest https://github.com/appium/appium-xcuitest-driver/blob/85833718a898c46c3dc2c96769dfd18608bb37bc/lib/commands/cookies.js. Tge Page definition as well, so maybe current remote debgger was wrongly sent null (but it does not matter), maybe.
`overrideUserAgent` probably can be used.
I haven't tested these yet.
Maybe we should move commands related to Page into another file for Page for readability, but this does not include such things.
---
https://github.com/appium/appium-xcuitest-driver/compare/add-some-remotedebugger?expand=1 is an example in the xcuitest driver repository
> chore: add commands for Page

- lib/mixins/execute.js
I can observe these param values are reset if the target web app/page crashes or is closed unexpectedly. Updated error messages might help one to find the cause. See https://dev.azure.com/AppiumCI/7a2a2919-d2b4-4720-a6c3-3a639f9bb2e0/_apis/build/builds/24988/logs/142 for an example of such crash
> chore: Improve error messages on missing params

- .github/workflows/functional-test.yml
although I'm not familiar with GitHub actions, updated based on https://github.com/actions/runner-images/blob/main/images/macos/macos-13-Readme.md#xcode
> ci: bump up ios versions, device, xcode and macos version under test

- lib/mixins/connect.js
Currently the value of retryCount is always 0
> fix: Properly log retries count

- lib/mixins/navigate.js
It did a few more tests.
Then, once this timeout occurs, `driver.title` etc also no longer gets a response. So, maybe it would be helpful to notify if an error occurred explicitly as the response for users so that they can end the session or restart the Safari process rather than silently fail and wait for long response time without any response (and eventually should kill the session or appium process)
> chore: return timeout error

- lib/mixins/navigate.js
Currently no URL validation is performed, which makes the remote debugger to wait for a page until timeout happens if the given URL is invalid. This PR fixes that
> chore: Perform URL validation

- lib/mixins/navigate.js
- lib/remote-debugger.js
- lib/rpc/constants.js
- lib/rpc/index.js
- lib/rpc/rpc-client.js
I've noticed we always experience page load timeouts for web pages like WDA's /health one. The reason for it is it's actually not a real page, but just a text, so it does not trigger the `Page.loadEventFired` event  like other "normal" pages.
> fix: Improve page load detection logic

- lib/mixins/connect.js
- lib/mixins/message-handlers.js
- lib/mixins/navigate.js
- lib/remote-debugger.js
- test/unit/mixins/navigate-specs.js
closes https://github.com/appium/appium-remote-debugger/issues/315
We could support pageLoadStrategy in `document.readyState` step case. In case a webpage issues `Page.loadEventFire` properly, this will not change the behavior so much.
Keyword | Page load strategy state | Document readiness state
-- | -- | --
"none" | none |  
"eager" | eager | "interactive"
"normal" | normal | "complete"
The input variation will be handled by https://github.com/appium/appium-xcuitest-driver/pull/2411
> feat: support pageLoadStrategy in readState check

- .github/workflows/functional-test.yml
- lib/mixins/connect.js
- lib/mixins/message-handlers.js
- lib/remote-debugger.js
- lib/rpc/rpc-client.js
- lib/utils.js
- package.json
It looks like sometimes after we receive a notification about a new app connection no followup pages update notification is delivered. This PR tries to streamline the flow and avoid performing any actions on the app until we actually have the list of pages. 
I've also updated/fixed some typedefs and removed the asynchronous lock as all operations on the `appDict` are synchronous and they don't need any locking
> fix: Tune page array retrieval

- .github/workflows/functional-test.yml
- test/functional/safari-e2e-specs.js
GH CI is slow, so more/longer retries are needed for integration tests to pass
> test: Tune integration tests

- lib/mixins/connect.js
- lib/mixins/cookies.js
- lib/mixins/events.js
- lib/mixins/execute.js
- lib/mixins/message-handlers.js
- lib/mixins/misc.js
- lib/mixins/navigate.js
- lib/mixins/property-accessors.ts
- lib/mixins/screenshot.js
- lib/remote-debugger.ts
It looks like typescript was not really happy about the hack with mixin interfaces (which works for Python, he-he).
So I have implemented them differently using package-private accessors to make the compiler happy
> fix: Properly handle protected accessors from mixin methods

- lib/mixins/navigate.js
Case without target provisioning event that this PR tries to address:
```
{"level":"VERBOSE","message":"[1a70c491][XCUITestDriver@339b] Attempting to set url 'http://127.0.0.1:8100/health'","timestamp":"2024-08-07 12:24:25.231"}
{"level":"VERBOSE","message":"[1a70c491][RemoteDebugger] Navigating to new URL: 'http://127.0.0.1:8100/health'","timestamp":"2024-08-07 12:24:25.232"}
{"level":"VERBOSE","message":"[1a70c491][RemoteDebugger] Sending '_rpc_forwardSocketData:' message to app 'PID:530', page '1', target 'page-11' (id: 30): 'Page.navigate'","timestamp":"2024-08-07 12:24:25.232"}
{"level":"VERBOSE","message":"[1a70c491][RemoteDebugger] Received data response from send (id: 30): '{}'","timestamp":"2024-08-07 12:24:25.262"}
{"level":"VERBOSE","message":"[1a70c491][RemoteDebugger] Pages …
```
> fix: Start page status monitoring on page change event as well

- lib/mixins/connect.js
- lib/remote-debugger.ts
It might be used to improve error messages
> feat: Expose appDict

- .github/workflows/functional-test.yml
- lib/remote-debugger.ts
- lib/rpc/remote-messages.js
- lib/rpc/rpc-client.js
- lib/types.ts
Internet says that Safari's remote debugger is fragile, that is why it makes sense to enable domains sequentially and in the particular order to avoid possible issues later.
> fix: Tune page initialization

- lib/mixins/connect.js
- lib/mixins/execute.js
- lib/mixins/navigate.js
- lib/protocol/index.js
- lib/rpc/constants.js
- lib/rpc/index.js
- lib/rpc/remote-messages.js
- lib/rpc/rpc-client-real-device.js
- lib/rpc/rpc-client-simulator.js
- lib/rpc/rpc-client.js
- lib/rpc/rpc-message-handler.js
- lib/types.ts
- lib/utils.js
- package.json
- test/functional/safari-e2e-specs.js
- test/unit/mixins/execute-specs.js
BREAKING CHANGE: Removed the obsolete ON_TARGET_PROVISIONED_EVENT exported constant
This change is quite large and introduces a couple of important fixes:
- Usage of `Target.setPauseOnStart` command. This allows to properly control the life cycle of targets allowing for proper target initialization before interacting with them.
- Better log messages
- Fixes related to data events emitting
- Better RPC synchronization and page state detection
> refactor: Introduce pauseOnStart for targets creation

- .github/workflows/functional-test.yml
- lib/remote-debugger-real-device.ts
- lib/remote-debugger.ts
- lib/rpc/rpc-client.js
I sometimes observe setContext timeouts due to slow CI env, for example https://github.com/appium/java-client/actions/runs/16948552767/job/48035614358#step:17:1511
> chore: Bump the default timeout for the target creation event

- package.json
BREAKING CHANGE: Required Node.js version has been bumped to ^20.19.0 || ^22.12.0 || >=24.0.0
BREAKING CHANGE: Required npm version has been bumped to >=10
BREAKING CHANGE: Required base driver version has been bumped to >=10.0.0-rc.1
> feat: Update server compatibility

- lib/rpc/rpc-client.js
We should not be able to send any requests to an app while any of its page is being initialized. Doing so may cause unexpected freezes or crashes
> fix: Apply initialisation lock per app

- .github/workflows/functional-test.yml
- lib/rpc/remote-messages.js
- lib/rpc/rpc-client.js
- lib/rpc/rpc-message-handler.js
Full target-based protocol support should be present since iOS 13.2 (year 2019). Our minimum major supported version is 17.
Also we do not run any tests to validate that legacy support.
BREAKING CHANGE: Changed constructor signature of RemoteMessages class. It does not accept any arguments now
BREAKING CHANGE: Removed the obsolete isTargetBased getter and setter from RemoteMessages class instances
BREAKING CHANGE: Removed the obsolete needsTarget getter and  isTargetBased property from RpcClient class instances
BREAKING CHANGE: Removed the obsolete isTargetBased getter and  setter from RpcClient class instances
BREAKING CHANGE: Changed constructor signature of RpcMessageHandler class. It does not accept any arguments now
BREAKING CHANGE: Removed the obsolete isTargetBased getter and …
> feat: Drop the obsolete non-target based communication protocol support

- lib/rpc/rpc-client.js
Resolves 
```
2025-10-03 07:56:52:470 - [6df9aeb9][HTTP] --> DELETE /session/6df9aeb9-8bc1-4c9e-b30d-7873316ecf63/window 
2025-10-03 07:56:52:470 - [6df9aeb9][XCUITestDriver@ba61] Calling AppiumDriver.closeWindow() with args: ["6df9aeb9-8bc1-4c9e-b30d-7873316ecf63"]
2025-10-03 07:56:52:471 - [6df9aeb9][XCUITestDriver@ba61] Executing command 'closeWindow'
2025-10-03 07:56:52:474 - [6df9aeb9][RemoteDebugger] Executing atom 'execute_script' with 'args=["setTimeout(function () {window.open('','_self').close();}, 0); return true;",[]]; frames='
2025-10-03 07:56:52:476 - [6df9aeb9][RemoteDebugger] Executing 'execute_script' atom in default context
2025-10-03 07:56:52:477 - [6df9aeb9][RemoteDebugger] Sending javascript command: '(function(){return (function(){var e=this||self...'
2025-10-03 …
```
> fix: Do not wait for existing targets
