lib/remote-debugger-rpc-client.js, lib/remote-debugger.js, package.json, test/unit/remote-debugger-specs.js
Fix the handling of `connect` when there are no apps present.
=> Fix handling of no apps

lib/remote-debugger-rpc-client.js, lib/remote-debugger.js, test/unit/remote-debugger-specs.js
We need to wait for the dom at one point. Also fix error
=> Fix handling of waiting for dom

lib/helpers.js, lib/remote-debugger-message-handler.js, lib/remote-debugger-rpc-client.js, lib/remote-debugger.js
Fix a couple of problems.
a) allow `null` to be a valid response
b) socket error event listeners
=> Fix event listener error

lib/remote-debugger-message-handler.js, lib/remote-debugger-rpc-client.js, lib/remote-debugger.js, test/unit/remote-debugger-specs.js
Timeline events were not being handled correctly. Fix.
=> Fix handling of timeline events

lib/remote-debugger.js
Implements https://github.com/appium/appium/pull/5836
Needs to be coordinated with https://github.com/appium/appium-ios-driver/pull/45
=> Add support for checking current url

lib/remote-debugger-rpc-client.js, lib/remote-debugger.js
Sometimes connection gets messed up because redirects come in too fast. Try to keep track of things.
=> Perhaps fix handling of connect

lib/helpers.js, lib/remote-debugger-message-handler.js, lib/remote-debugger-rpc-client.js, lib/remote-debugger.js
When we have apps that are proxies of other apps, we need to check all of them, not just a single one like we were.
=> Try out all the proxy ids we get, not just the first

lib/helpers.js, lib/remote-debugger-message-handler.js, lib/remote-debugger-rpc-client.js, lib/remote-debugger.js, test/helpers/remote-debugger-server.js
Wrap and upwrap the special message handler so we don't lose it in the course of operating. Also clean up handling of error listener.
=> Clean up special message handling

lib/remote-debugger.js
As per @jlipps' comment https://github.com/appium/appium-remote-debugger/pull/24/files/45e3bca583adc39cdfbf1b7cf46a9ef75742b23c#r69344300
=> Clean up loop handling

lib/message-handlers.js, lib/remote-debugger-rpc-client.js
Just make it a little clearer what is going on.
=> Add message to app connection

lib/message-handlers.js, lib/remote-debugger-message-handler.js, lib/remote-debugger.js, test/unit/remote-debugger-specs.js
Otherwise we can get events after we take the session as over.
=> Make sure we cleanup handlers when disconnecting

lib/message-handlers.js
We are having some problems in Travis with apps disconnecting and the wrong things happening. This logging will provide some visibility and a solution, I hope.
=> Better logging for disconnect

.eslintrc, lib/helpers.js, lib/remote-debugger.js, lib/remote-messages.js, package.json, test/unit/remote-debugger-specs.js, test/unit/remote-messages-specs.js
Make the system a little better.
=> Add eslint and pre-commit checks

lib/remote-debugger.js
make sure we filter out pages as per ignoreAboutBlankUrl and currentUrl values
=> make sure we filter out pages correctly

lib/webkit-remote-debugger.js
This is already done for simulator. Applying same for real devices
=> filter out pages empty url for real devices. 

lib/remote-debugger.js
Make it a little cleaner and more informative.
=> Clean up logging of connection process

package.json, test/helpers/server-setup.js, test/unit/helpers-specs.js, test/unit/remote-debugger-specs.js, test/unit/remote-messages-specs.js, test/unit/webkit-remote-debugger-specs.js
https://github.com/appium/appium/issues/10016
=> Stop using arrow functions in mocha

lib/remote-debugger-message-handler.js, lib/remote-debugger-rpc-client.js, lib/remote-debugger.js, lib/remote-messages.js
I was doing some research on how I could access the webkit devtools protocol using appium-remote-debugger and tweaked around with the code. Feel free to merge this if you think it might become handy one day.
=> Propagate network events

lib/remote-debugger-rpc-client.js, test/helpers/remote-debugger-server.js
Part of https://github.com/appium/appium/issues/10685
=> Fix buffer usage

lib/webkit-rpc-client.js, package.json
Partially addresses the issue described in https://github.com/appium/appium/issues/10904
=> Avoid timeout exceptions while resolving promises

lib/webkit-rpc-client.js
The previous code did not always work the way I wanted. This fix should improve the situation.
=> Tune switch usage for message handlers

lib/remote-debugger-rpc-client.js, lib/remote-debugger.js
All further info regarding this pull request can be found at https://github.com/appium/appium/pull/10960
=> Add option to use a remote debugger proxy

lib/webkit-rpc-client.js
https://github.com/appium/appium/issues/11131
=> Properly catch warnings inside rejectCall

lib/message-handlers.js, lib/remote-debugger-message-handler.js, lib/remote-debugger-rpc-client.js, lib/remote-debugger.js, test/helpers/remote-debugger-server.js
Some minor changes. The substantive change is to emit an event when frames detach. This will allow us to void the frames in the drivers.
=> Emit event when frame detaches

lib/remote-debugger-rpc-client.js, lib/remote-debugger.js
It looks like sometimes the garbage collection operation freezes for too long. Lets make timeout to happen if this situation occurs.
=> Add the default timeout to garbage collection

lib/remote-debugger-rpc-client.js, test/helpers/helpers.js, test/helpers/remote-debugger-server.js
On Travis the data often gets chunked and causes flakiness. Simply cache the chunk and wait for the next one.
=> Fix test server for chunked data

.travis.yml, lib/remote-debugger.js, package.json, test/functional/http-server.js, test/functional/safari-e2e-specs.js
Add some basic tests with simulators.
=> Add basic functional tests

lib/remote-debugger-message-handler.js, lib/remote-debugger-rpc-client.js, lib/remote-messages.js, lib/rpc-client.js, lib/webkit-rpc-client.js
There have been problems where the wrong communication system is used. This PR changes the logic so that the initial condition is based on what seems to be right, but then if the error comes in that the domain is not know, we switch to the other protocol.
See: 
https://github.com/appium/appium/issues/12518
https://github.com/appium/appium/issues/12510
=> Dynamically change communication protocol

lib/remote-debugger.js
The waits will be accommodated by the retries.
=> perf: Do not wait for promises when not necessary

lib/remote-debugger-message-handler.js, lib/rpc-client-real-device.js, lib/rpc-client-simulator.js, lib/rpc-client.js, package.json
`appium-ios-device` already does the parsing of plists perfectly well, so use it.
=> refactor: reuse the webinspectorservice for simulators

test/functional/safari-e2e-specs.js
The Xcode 11/iOS 13 tests fail because of sim startup failures (partly, I think, because Travis refuses to update the beta of Xcode 11). Limit time to failure, and retry.
=> tests: fix flakey e2e tests

lib/helpers.js, lib/rpc-client.js
Mostly address comments from #165 which I merged accidentally.
=> refactor: clean up send and parse

lib/remote-debugger.js
Try to fix https://github.com/appium/appium/issues/13569
=> Exclude the treatment of WebViews from non-active applications

.travis.yml, lib/atoms.js, lib/logger.js, lib/remote-debugger-message-handler.js, lib/remote-debugger-real-device.js, lib/remote-debugger.js, lib/remote-messages.js, lib/rpc-client-real-device.js, lib/rpc-client-simulator.js, lib/rpc-client.js, package.json, test/functional/safari-e2e-specs.js
Pass through the logging of communication, and chunk size.
=> fix: use web inspector service verbose and chunk size parameters

.travis.yml, package.json, test/functional/html/index.html, test/functional/html/shadow-dom.html, test/functional/http-server.js, test/functional/safari-e2e-specs.js
Make sure it works at this level.
=> tests: add test for handling of shadow DOM

lib/remote-debugger.js, lib/remote-messages.js, lib/rpc-client.js, lib/rpc-message-handler.js, test/unit/remote-messages-specs.js
Much of this is refactoring to organize the messages. And then add the possibility to do every step that desktop safari does when you start a web inspector debugging session. This is turned off by default. 
Once this is in I have some work to simplify things.
=> Feat: add possibility of full initialization if web inspector. 

lib/remote-messages.js, lib/rpc-client.js, lib/rpc-message-handler.js
Just making things a little clearer.
=> refactor: move to getter/setter for communication strategy

lib/helpers.js
=> fix: remove standard functions from return values

lib/remote-debugger-real-device.js, lib/remote-debugger.js, lib/rpc/rpc-client-real-device.js, lib/rpc/rpc-client-simulator.js, lib/rpc/rpc-client.js, package.json
https://github.com/appium/appium-ios-device/pull/73 and https://github.com/appium/appium/issues/14700
=> feat: add webInspectorMaxFrameLength option

lib/mixins/execute.js, lib/rpc/rpc-client.js, package.json, test/unit/mixins/execute-specs.js, test/unit/rpc/rpc-client-specs.js
attempts to address: https://github.com/appium/appium/issues/14867
=> retry if targetId had changed

ci-jobs/pr-validation.yml
=> ci: update ci env

bin/web_inspector_proxy.js, ci-jobs/templates/node-e2e-template.yml, gulpfile.js, lib/atoms.js, lib/logger.js, lib/mixins/connect.js, lib/mixins/execute.js, lib/mixins/navigate.js, lib/rpc/rpc-client.js, lib/rpc/rpc-message-handler.js, lib/utils.js, package.json, test/functional/http-server.js, test/functional/safari-e2e-specs.js
Similar to https://github.com/appium/appium-mac2-driver/pull/142
=> refactor: Set Appium as peer dependency

.github/workflows/publish.js.yml, bin/web_inspector_proxy.js, lib/atoms.js, lib/logger.js, lib/mixins/connect.js, lib/mixins/execute.js, lib/mixins/navigate.js, lib/rpc/rpc-client.js, lib/rpc/rpc-message-handler.js, lib/utils.js, package.json, test/functional/http-server.js, test/functional/safari-e2e-specs.js
Related to https://github.com/appium/appium/issues/17806
=> chore: Remove peer dependency to Appium

lib/protocol/index.js, lib/rpc/rpc-client.js, package.json
Update protocol from https://github.com/WebKit/webkit/tree/main/Source/JavaScriptCore/inspector/protocol
This does not change anything for existing commands since no new command is called. I have just added links to each protocol and add `disable` command and a few which might be interested in.
=> chore: update protocol a few and add links to each protocol

lib/remote-debugger.js
fix appium/appium#15685
did not test this but seems to be the cause of the problem
=> fix: use correct timeline rpc name

lib/protocol/index.js, lib/remote-debugger.js, test/functional/safari-e2e-specs.js
adding the possibility to capture viewport screenshots for safari
=> feat: add method to capture viewport

lib/mixins/connect.js, lib/mixins/message-handlers.js
Safari does not return any pages if it is not available for automation
=> fix: Only try to select Safari if it is enabled for automation

scripts/common.mjs
=> chore: remove unused arg in scripts/common.mjs

lib/mixins/misc.js, lib/remote-debugger.ts, test/functional/safari-e2e-specs.js
This method might be useful to report a better error message in the xcuitest driver
=> feat: Add a helper method to verify if javascript execution is blocked

lib/mixins/connect.js, lib/mixins/execute.js, lib/mixins/navigate.js, lib/rpc/rpc-client.js, test/functional/safari-e2e-specs.js
Sending of device commands might be stuck due to various reasons. This fix ensures we never have a deadlock situation in such case
=> fix: Avoid deadlocks
